[buildPlans.IosevkaViper]
family = "Iosevka Viper"
spacing = "normal"
serifs = "sans"
noCvSs = false
webfontFormats = ["WOFF2"]
exportGlyphNames = false
noLigation = true

  [buildPlans.IosevkaViper.variants]
  inherits = "ss14"

  [buildPlans.IosevkaViper.variants.design]
    x = "curly-serifless"
    i = "flat-tailed"
    l = "serifed-flat-tailed"
    zero = "slashed"
    pilcrow = "high"
    caret = "low"
    paren = "normal"
    brace = "straight"
    number-sign = "upright"
    ampersand = "closed"
    dollar = "open-cap"
    bar = "force-upright"
    question = "smooth"
    one = "no-base"
    seven = "bend-serifless"
    w = "straight-flat-top-serifless"

[buildPlans.IosevkaViper.widths.Normal]
shape = 500
menu = 5
css = "normal"
