[buildPlans.iosevka-normal]
family = "iosevka-normal"
spacing = "normal"
serifs = "sans"
noCvSs = true
webfontFormats = ["woff2"]

  [buildPlans.iosevka-normal.variants]
  inherits = "ss14"

  [buildPlans.iosevka-normal.ligations]
  inherits = "clike"

  [buildPlans.iosevka-normal.variants.design]
    x = "curly-serifless"
    i = "flat-tailed"
    l = "serifed-flat-tailed"
    zero = "slashed"
    pilcrow = "high"
    caret = "low"
    paren = "normal"
    brace = "straight"
    number-sign = "upright"
    ampersand = "closed"
    dollar = "open-cap"
    bar = "force-upright"
    question = "smooth"

[buildPlans.iosevka-normal.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-normal.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-normal.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-normal.weights.bold]
shape = 700
menu = 700
css = 700
