# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  iosevka = {
    pname = "iosevka";
    version = "v34.6.3";
    src = fetchTarball {
      url = "https://github.com/be5invis/Iosevka/archive/v34.6.3.tar.gz";
      sha256 = "sha256-fd1yi5tNNixedUMvoiJIpg4RF9omAJTAb2TD1B7bqV4=";
    };
  };
}
