# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  iosevka = {
    pname = "iosevka";
    version = "v33.1.0";
    src = fetchTarball {
      url = "https://github.com/be5invis/Iosevka/archive/v33.1.0.tar.gz";
      sha256 = "sha256-34TTyv9EShZSqJy0HCs0RZrDE38DIFMqkrxo/I03HEs=";
    };
  };
}
